# Generated by Django 5.0 on 2023-12-08 20:09

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transaccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hash", models.CharField(max_length=100)),
                ("cantidad", models.DecimalField(decimal_places=2, max_digits=10)),
                ("emisor", models.CharField(max_length=100)),
                ("receptor", models.CharField(max_length=100)),
            ],
        ),
    ]
